version: '3.7'
networks:
    app-tier:
        driver: bridge
services:
  nextjs: 
    container_name: bomsbro-blog-web-app
    build: ./
    ports:
      - '3000:3000'
    expose:
      - '3000'
    restart: always
  nginx: 
    container_name: bomsbro-reverse-proxy
    build: ./nginx
    volumes:
      - /var/data/certbot/conf:/etc/letsencrypt # for ssl certification
      - /var/data/certbot/www:/var/www/certbot # for ssl certification
      - /var/data/nginx # for default config
    restart: always
  certbot: # certbot for ssl certification
    container_name: certbot-for-ssl
    image: certbot/certbot
    volumes:
      - /var/data/certbot/conf:/etc/letsencrypt # for ssl certification
      - /var/data/certbot/www:/var/www/certbot # for ssl certification
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
